name: Forest Boy
favicon: null
layout_spectrum: 0.89225
typography_spectrum: 0.53266
title: Forest Boy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#10100d'
    - '#4a7022'
    - '#988a7e'
    - '#b2c199'
  brandStrength: 0.375
  lightness: 0.25
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
