name: Forest Boy
favicon: null
layout_spectrum: 0.67209
typography_spectrum: 0.07684
title: Forest Boy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#34343e'
    - '#c9caa2'
    - '#9f9b75'
    - '#565f5c'
    - '#848365'
  brandStrength: 0.5625
  lightness: 0.25
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
