name: Forest Boy
favicon: null
layout_spectrum: 0.29366668011061847
typography_spectrum: 0.6814999235793948
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3101037796586752
  lightness: 0.09417535876855254
  saturation: 0.8259571846574545
  rhythmicContrast: 0.7780708307400346
purpose: []
